# Generated by Django 4.1.6 on 2023-02-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumbotron_image', models.ImageField(upload_to='')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.anime')),
            ],
        ),
    ]
