# Generated by Django 4.1.6 on 2023-03-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animegenre',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anime', to='main.anime'),
        ),
        migrations.AlterField(
            model_name='animegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='genre', to='main.genre'),
        ),
    ]
