# Generated by Django 4.1.6 on 2023-03-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_anime_description_remove_anime_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='jumbotron_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
